### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ProfessorQu** [ProfessorQu/Starcraft-Bot#1]
This is everything I still have todo before being done:

### Planned:
- [x] Build first few structures near ramp (build wall-off)
- [x] Put a Stalker/Zealot to finish the wall-off
- [x] Warp in defensive Stalkers near the main base
- [x] Add Photon Cannons to defend so I can have more offensive Stalkers
- [x] Document the entire strategy
- [x] Add more documentation
- [x] Add more debug information
- [x] Have defending Stalkers per base
- [ ] Build a Pylon per base to build Photon Cannons next to

### Whenever I feel like it:
- [ ] Create my own distribute workers function for optimal Stalkers
- [x] Use WSL/Docker/VM to run games headless (used Docker)
- [ ] Build Robotics Facility
- [ ] Build Observer (for detection and scouting)
- [ ] Build Colossus
- [x] Build the proxy Pylon less randomly (Stalkers wander too far away because of cliffs)
- [x] Attack when certain events are triggered (e.g. Weapons finished)
- [ ] Research Blink
- [ ] Micro Stalkers (using Blink and moving)
